# Generated by Django 4.1.6 on 2023-02-09 23:28

import django.core.validators
from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(max_length=50, validators=[team.models.validate_phonenumber])),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
